"""Web3 root authority whitelist — official domains and Twitter handles.

Used by the Verifier's Layer 1 (Origin Check) to anchor identity.
Updated periodically from RootData / DefiLlama.
"""

# Official domains of top L1/L2 foundations and blue-chip protocols
OFFICIAL_DOMAINS = {
    # L1 / L2 Foundations
    "ethereum.org",
    "ethereum.foundation",
    "consensys.io",
    "solana.com",
    "solana.org",
    "sui.io",
    "stellar.org",
    "aptosfoundation.org",
    "aptoslabs.com",
    "near.org",
    "starkware.co",
    "starknet.io",
    "polygon.technology",
    "polygon.com",
    "avax.network",
    "avalanche.com",
    "arbitrum.io",
    "arbitrum.foundation",
    "optimism.io",
    "base.org",
    "zksync.io",
    "scroll.io",
    "linea.build",
    "mantle.xyz",
    "celestia.org",
    "cosmos.network",
    "polkadot.network",
    "kusama.network",

    # Blue-chip protocols
    "uniswap.org",
    "aave.com",
    "curve.fi",
    "makerdao.com",
    "lido.fi",
    "eigenlayer.xyz",
    "chain.link",
    "compound.finance",
    "ens.domains",
    "thegraph.com",
    "balancer.fi",
    "yearn.fi",
    "convexfinance.com",
    "frax.finance",

    # Grant / Hackathon platforms
    "gitcoin.co",
    "immunefi.com",
    "hackerone.com",
    "bugcrowd.com",
    "dorahacks.io",
    "devpost.com",
    "ethglobal.com",
    "superteam.fun",
    "layer3.xyz",
    "onlydust.com",
    "dework.xyz",
    "questbook.xyz",
    "hackenproof.com",
    "code4rena.com",
    "sherlock.xyz",
    "cantina.xyz",

    # Governance / Forums
    "gov.optimism.io",
    "governance.aave.com",
    "gov.uniswap.org",
    "forum.arbitrum.foundation",
    "research.lido.fi",
    "forum.polygon.technology",
    "governance.decentraland.org",

    # Research / Data
    "defillama.com",
    "rootdata.com",
    "messari.io",
    "dune.com",
    "nansen.ai",
    "theblock.co",
    "coindesk.com",
    "cointelegraph.com",
}


# Official Twitter/X handles of foundations and protocols (without @)
OFFICIAL_TWITTER_HANDLES = {
    "ethereum",
    "ethereumfndn",
    "EF_ESP",
    "solana",
    "solanaFndn",
    "suinetwork",
    "SuiFoundation",
    "Mysten_Labs",
    "StellarOrg",
    "StellarDev",
    "Aptos",
    "AptosLabs",
    "NEARProtocol",
    "StarknetFndn",
    "StarkWareLtd",
    "0xPolygonFndn",
    "0xPolygon",
    "arbitrum",
    "arbitrumFndn",
    "optimism",
    "OptimismGov",
    "buildonbase",
    "zksync",
    "Scroll_ZKP",
    "LineaBuild",
    "Uniswap",
    "UniswapFnd",
    "AaveAave",
    "AaveGrants",
    "CurveFinance",
    "MakerDAO",
    "LidoFinance",
    "eigenlayer",
    "chainlink",
    "compoundfinance",
    "ensdomains",
    "graphprotocol",
    "gitcoin",
    "immunefi",
    "hackerone",
    "DoraHacks",
    "devpost",
    "ETHGlobal",
    "SuperteamDAO",
    "Layer3xyz",
    "defillama",
    "RootDataLab",
    "CertiK",
    "GoPlusSecurity",
    "SlowMist_Team",
    "PeckShieldAlert",
}
